version: 2

job_defaults: &job_defaults
  docker:
    - image: circleci/node:latest-browsers
  working_directory: ~/project/repo

cache_key: &cache_key
  key: frontal-dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}

jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          <<: *cache_key
          paths:
            - node_modules

  lint:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: lint
          command: npm run lint

  test:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: test
          command: npm test

  e2e:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: e2e
          command: npm run e2e

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
